-- QUERY 18: EMPLOYEE ATTENDING ALL EVENTS
-- PROBLEM STATEMENT: 
-- Find out the employees who attended all the company events.						
-- OUTPUT	
-- EMPLOYEE_NAME	NO_OF_EVENTS
-- Charles				3
-- Sainz				3

SELECT * FROM emp_day_18;
SELECT * FROM events_day_18;

SELECT COUNT(*) FROM emp_day_18;
SELECT COUNT(distinct EVENT_NAME) FROM events_day_18;

WITH CTE AS
(SELECT DISTINCT EV.EMP_ID, EM.NAME, EV.EVENT_NAME AS CNT FROM events_day_18 EV
JOIN emp_day_18 EM ON EV.EMP_ID = EM.ID
GROUP BY EV.EMP_ID, EM.NAME, EV.EVENT_NAME
ORDER BY 1)
SELECT DISTINCT NAME AS EMPLOYEE_NAME, COUNT(CNT) AS NO_OF_EVENTS
FROM CTE
GROUP BY NAME
HAVING NO_OF_EVENTS = (SELECT COUNT(DISTINCT EVENT_NAME) FROM events_day_18);
